### ISSUE TITLE
[SOLVED] Broken napiprojekt plugin

### ISSUE THREAD

**Issue by fenuks** [keskad/subget#13]
Hi.
Napiprojekt plugin downloads empty file. I had tried download subtitles for various files and result is same, empty txt file. Another plugins works fine for me.

I also would like to suggest some changes:
-sorting by subtitles language
-when searching subtitles for multiple files subtitles for file A, should be separated from subtitles for file B
-possibility to adding folders to queue
-user interface is, well poor, essential actions as adding files or clearing list should be available as icons on toolbar, it's one mouse click less
-shortkeys are... strange, "About Subget" has its shortkey and "Clear list" doesn't, which is more important, best solution is allow user to define his own shortkeys
-double clicking on subtitle in the list should download it
-automatic subtitle download based on some criteria, for example name of subtitle is same as file and language is XX
-'silent saving' without Save as.. dialog (this behaviour should be changeable in preferences)
-searching only in certain languages

Program is promising, but still need a lot of effort and sleepless night;). Hope you will find time to continue improving it.

**Comment by keskad** [comment]
Hello,
Thanks for your feedback.

The napiprojekt plugin requires 7zip package to download subtitles
correctly.
- sorting subtitles by language # im working on it
- possibility to adding folders to queue # it should be easy to
  implement
- user interface is, well poor, essential actions as adding files or
  clearing list should be available as icons on toolbar, it's one mouse
  click less # i agree, the toolbar will be implemented
- double clicking on subtitle in the list should download it # will be implemented
- searching only in certain languages # i will implement it
- 'silent saving' without Save as.. dialog (this behaviour should be changeable in preferences) # definitely you have right
- shortkeys are... strange, "About Subget" has its shortkey and "Clear list" doesn't, which is more important, best solution is allow user to define his own shortkeys # i will try to implement this feature
- when searching subtitles for multiple files subtitles for file A, should be separated from subtitles for file B # i think it will be hard to implement, it goes to end of my queue now

I should have some time in upcoming few days, some of these features should be implemented soon.

Thank you.

**Comment by fenuks** [comment]
Thanks. I forgot to mention that I am running Fedora 16. There strange thing. I am pretty sure that I had p7zip installed. Probably it was removed during update to 'Verne'. Never mind. I installed it and p7zip-plugins package and now plugin works like a charm. Sorry for false alarm.

Here's one more thing I found useful. It will be great if user could set which encoding should be used.

**Comment by keskad** [comment]
That's no problem mate. And thank you for your feedback. I see you are new at github, you can follow the project using "Watch" button if you want - you will get all informations about changes in subget.

Maybe today i will implement some of functions from your list.

**Comment by keskad** [comment]
'double clicking on subtitle in the list should download it"

Implmented.

**Comment by keskad** [comment]
"user interface is, well poor, essential actions as adding files or clearing list should be available as icons on toolbar, it's one mouse click less # i agree, the toolbar will be implemented"

Fixed with commit (https://github.com/webnull/subget/commit/ea773a4b791cd5847c31270aacf69b090c29d02b)

**Comment by fenuks** [comment]
Good job. I've tested changes you made and they work just as they should. If we're talking about changes I have two new ideas which are:
1. change list to another one which allow select more than one result in order to download a few subtitles at once
2. progress indicator when subget is searching for subtitles, some plugins show their results faster than others and its hard to decide if subget stopped searching or is still looking for subtitles.

**Comment by keskad** [comment]
Oh, you have great ideas. Thank you. I think the progress indicator is neccessary.
And downloading many subtitles at one time should not be a big problem.

But now i think i must first focus on these features:
- sorting subtitles by language
- possibility to adding folders to queue
- searching only in certain languages
- 'silent saving' without Save as.. dialog (this behaviour should be changeable in preferences)

I will search now for progress indication in PyGTK, if it will be easy to implement i think i would implement it today, if not - just later.

Thanks for your participation, if you will have any more ideas - please tell me :-)
Maybe you can help me translate application to non-english language?

**Comment by fenuks** [comment]
Thanks ;-)
There is no rush in adding these features. The ones you listed are more important. 
I would love to help translate, but unfortunately know (poorly) English, Polish and some Spanish (real basics). I was force learning German for 6 long years in school, but I barely know how to introduce myself (my sister know German really good, so I can ask her to translate subget). In free time I want to learn Japanese, so maybe someday I will translate subget to language understandable to people from Land of the Rising Sun ;P. If I can participate in any other way, feel free to tell me and I will do my best.

**Comment by keskad** [comment]
Oh, that would be great if you could do German translation.

All you need is to replace Polish strings with German.
https://github.com/webnull/subget/blob/master/usr/share/subget/locale/pl/LC_MESSAGES/subget-src.po

And ready to use translation you can send me via https://gist.github.com/

**Comment by keskad** [comment]
"If I can participate in any other way, feel free to tell me and I will do my best."

So, what you can do? I would be thankful for programming, translating, creating wiki, suggesting ideas,  porting to Windows or Mac.
