### ISSUE TITLE
" 'language' is not defined " // deb

### ISSUE THREAD

**Issue by mwarzynski** [keskad/subget#19]
Subget:
Wersja: 1.6.4, Linux

PC:
Kernel: 2.6.32-5-686
System: Crunchbang Linux

Błąd występuje po instalacji subgeta z paczki *.deb pobranej z 'Paczkowni' - przy próbie wyszukania napisów.
Próbowałem uruchomić subgeta na Debian Testing (G3) jak i Crunchbang Linux (the newest version). Cały czas to samo.

Log:

Traceback (most recent call last):
  File "/usr/bin/subget", line 1285, in gtkDoSearch
    self.plugins[Plugin].language = language
NameError: global name 'language' is not defined

**Comment by keskad** [comment]
Proszę podać wersję Subgeta, do paczkowni co kilka dni bez przerwy wpływają nowe paczki z nowymi wersjami Subgeta.

**Comment by mwarzynski** [comment]
Spróbowałem odpalić subgeta z desktopa.

Desktop:
System: Gentoo Linux
Kernel: 3.3.8-gentoo
Środowisko: KDE 4.8.3

http://pastebin.com/MF5WNM96 // subgeta ściągałem z gita - najnowsza wersja (1.6.5?)

Czy problemem może być używanie python2.7?

**Comment by keskad** [comment]
Któraś wtyczka wysypuje się przy wyszukiwaniu przy pomocy słów kluczowych, no cóż, będę musiał sam znaleźć ten błąd.

**Comment by keskad** [comment]
Dnia 2012-08-30, o godz. 05:27:09
LnxMeN notifications@github.com napisał(a):

> Spróbowałem odpalić subgeta z desktopa.
> 
> Desktop:
> System: Gentoo Linux
> Kernel: 3.3.8-gentoo
> Środowisko: KDE 4.8.3
> 
> http://pastebin.com/MF5WNM96 // subgeta ściągałem z gita - najnowsza
> wersja (1.6.5?)
> 
> Czy problemem może być używanie python2.7?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webnull/subget/issues/19#issuecomment-8157631

Ten bug został prawdopodobnie naprawiony w najnowszym wydaniu Subgeta,
zapraszam do testowania.

**Comment by mwarzynski** [comment]
System: Gentoo Linux
 Kernel: 3.4.9-gentoo
 Środowisko: KDE 4.8.3
Python: 2.7

Log:
Traceback (most recent call last):
  File "/usr/bin/subget", line 1285, in gtkDoSearch
    self.plugins[Plugin].language = language
NameError: global name 'language' is not defined

Niestety problem nadal występuje.

**Comment by keskad** [comment]
Fixed.
