### ISSUE TITLE
cannot autostart media player

### ISSUE THREAD

**Issue by krzysztof-indyk** [keskad/subget#21]
hi!
It is not possible to autostart media player, because 
after receiving subtitles, application is closing and the message in terminal appears:

<pre>
28/04/2013 22:15:43, sendEvent: libnotify -> subget:: <b>Pobrano napisy dla pliku:<br/> filename</b><br/>Miłego oglądania!

(subget:16648): libnotify-WARNING **: you must call notify_init() before showing
**
libnotify:ERROR:notification.c:568:notify_notification_show: code should not be reached
Przerwane (core dumped)
</pre>

system: ubuntu 12.10 64bit
subget: v.1.7.6

**Comment by keskad** [comment]
Dnia 2013-04-28, o godz. 13:37:53
krise3k notifications@github.com napisał(a):

> hi!
> It is not possible to autostart media player, because 
> after receiving subtitles, application is closing and the message in
> terminal appears: <pre>
> 28/04/2013 22:15:43, sendEvent: libnotify -> subget:: <b>Pobrano
> napisy dla pliku:<br/> filename</b><br/>Miłego oglądania!
> 
> (subget:16648): libnotify-WARNING *_: you must call notify_init()
> before showing *_
> libnotify:ERROR:notification.c:568:notify_notification_show: code
> should not be reached Przerwane (core dumped)
> </pre>
> system: ubuntu 12.10 64bit
> subget: v.1.7.6
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webnull/subget/issues/21

Thank you for your report.
I will look at this problem as soon as possible.

Yours,
Damian Kęska
