### ISSUE TITLE
rgg4r2g245x2g45

### ISSUE THREAD

**Issue by ghost** [keskad/subget#23]
453g453

**Comment by keskad** [comment]
Witam.

Kiedyś było ale zniknęło. Może za jakiś czas na nowym serwerze dedykowanym postawimy repozytoria, ale najpierw stworzymy jakieś skrypty do budowania paczek.

Na chwilę obecną proszę użyć skryptu instalacyjnego - i tak poza tym dużo aktualizacji nie jest wprowadzanych ze względu na brak czasu oraz stwierdzenie, że całość jest całkiem stabilna tak więc bugi poprawiamy ale aktualnie nie szykują się żadne większe prace nad rozwojem nowych funkcji. Nie chcę nic oficjalnie mówić, ale chodził mi po głowie pomysł aby przepisać wszystko w stworzonym frameworku od zera, przenieść kod wtyczek, interfejs zrobić w QT.

Pozdrawiam,
Damian Kęska

**Comment by ghost** [comment]
g54c34545

**Comment by keskad** [comment]
Zależności jest mało. Bałaganu na pewno nie będzie ;) To jest aplikacja napisana w Pythonie, nie wymaga kompilacji - sama się instaluje tam gdzie trzeba 3 poleceniami.

**Comment by ghost** [comment]
gx4t343x342

**Comment by keskad** [comment]
Proszę spróbować jeszcze to: sudo ln -s /usr/local/share/subget/ /usr/share/subget

**Comment by ghost** [comment]
g5h4454g52c

**Comment by keskad** [comment]
Zdaję sobie sprawę z tego, że integracja z nautilusem może nie działać już poprawnie gdyż testowaliśmy to jeszcze z GNOME 2 :) Wiem, że trzeba by było zabrać się za przepisywanie kodu na QT albo Glade ale nie ma ostatnio kiedy się za to zabrać :) A można by było zreaktywować projekt stawiając go na nogi na porządnych podstawach. Bo to co zostało stworzone to był właściwie eksperyment który pomimo wszystko działa, lecz kod ma jakości studenckiej można to tak nazwać ;)
