### ISSUE TITLE
Errors in Ubuntu 11.10 with Gnome Shell

### ISSUE THREAD

**Issue by vbert** [keskad/subget#9]
1. **Error no 1:**
    Gdk:ERROR:/build/buildd/gtk+2.0-2.24.6/gdk/gdkregion-generic.c:1110:miUnionNonO: assertion failed: (y1 < y2)
    Przerwane
2. **Error no 2:**
    MANY:
    [addSubtitlesRow] sa.xpm nie istnieje, użyję domyślnej unknown.xpm
    [addSubtitlesRow] sa.xpm nie istnieje, użyję domyślnej unknown.xpm
    [addSubtitlesRow] vn.xpm nie istnieje, użyję domyślnej unknown.xpm

/usr/bin/subget:574: GtkWarning: Unable to retrieve the file info for        `file:///home/vbert/Wideo/Terra.Nova.S01E07.720p.HDTV.X264-DIMENSION/Terra.Nova.S01E07.720p.HDTV.X264-DIMENSION.mkv.txt': Błąd podczas wyznaczania pliku "/home/vbert/Wideo/Terra.Nova.S01E07.720p.HDTV.X264-DIMENSION/Terra.Nova.S01E07.720p.HDTV.X264-DIMENSION.mkv.txt": Nie ma takiego pliku ani katalogu
  response = chooser.run()

**Comment by keskad** [comment]
I can't control the GTK message (it isn't a python's exception), so it will still appear in console until i find workaround on this problem.

But the subtitles are appearing normally in place where do you pointed?
If downloaded text file with subtitles is 0 bytes size you need to install p7zip (p7zip-full in Ubuntu - Debian based), because it's required to unpack compressed subtitles.

**Comment by keskad** [comment]
/usr/bin/subget:574: GtkWarning: Unable to retrieve the file info for `file:///media/Movies/Keith.2008.avi.txt': Błąd podczas wyznaczania pliku "/media/Movies/Keith.2008.avi.txt": Nie ma takiego pliku ani katalogu
  response = chooser.run()
^CTraceback (most recent call last):
  File "/usr/bin/subget", line 1831, in <module>
    SubgetMain.main()
  File "/usr/bin/subget", line 273, in main
    self.graphicalMode(args)
  File "/usr/bin/subget", line 1763, in graphicalMode
    gtk.main()
KeyboardInterrupt
webnull@webnull-gentoo-desktop ~ $ du -sh /media/Movies/Keith.2008.avi.txt 
56K     /media/Movies/Keith.2008.avi.txt

Indeed i've got the same error but the application is still working.

**Comment by vbert** [comment]
I have installed: p7zip and p7zip-full.

Files with subtitles actually take, but in the console:

vbert@d830:~ $ subget
/usr/bin/subget:574: GtkWarning: Unable to retrieve the file info for `file:///home/vbert/Wideo/Cars.2.DVDRip.XviD-iMBT/Cars.2.2011.DVDRip.XviD-iMBT.CD1.srt.txt': Błąd podczas wyznaczania pliku "/home/vbert/Wideo/Cars.2.DVDRip.XviD-iMBT/Cars.2.2011.DVDRip.XviD-iMBT.CD1.srt.txt": Nie ma takiego pliku ani katalogu
  response = chooser.run()

**Comment by keskad** [comment]
So, thank you anyway for your involvement, i will work to fix this bug in next commit.
